package demo

import (
	"github.com/gin-gonic/gin"
)

//go:generate genny -in view.tpl -pkg ${GOPACKAGE} -out autogenerated_views.go gen TYPE=Pair

func route(enging *gin.Engine) {
	enging.GET("/", IndexView)

	enging.Group("/api")
	{
		enging.GET("/pairs/:id", RetrievePairView)
		enging.DELETE("/pairs/:id", DeletePairView)
		enging.GET("/pairs/", ListPairView)
		enging.PUT("/pairs/", CreatePairView)
		enging.POST("/pairs/", UpdatePairView)
	}
}
