package models

import "time"

// Pair :
// gen:qs
//go:generate goqueryset -in ${GOFILE} -out autogenerated_qs_${GOFILE}
type Pair struct {
	ID        int        `gorm:"primary_key,column:id" json:"id"`
	CreatedAt time.Time  `gorm:"column:create_at" json:"create_at"`
	UpdatedAt time.Time  `gorm:"column:update_at" json:"update_at"`
	DeletedAt *time.Time `gorm:"column:deleted_at" sql:"index" json:"-"`
	Key       string     `gorm:"type:varchar(100);unique_index,column:key" json:"key"`
	Value     string     `gorm:"size:255,column:value" json:"value"`
}
